[package]
name = "apex"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "^1.0", features = ["full"] }
hyper = { version = "^1.0", features = ["full"] }
hyper-util = { version = "^0.1", features = ["tokio"] }
http = "^1.0"
http-body-util = "^0.1"
bytes = "^1.0"
futures-util = "^0.3"
tower = "^0.5"
axum = { version = "^0.8" }
proc-macro2 = "^1.0"
quote = "^1.0"
syn = { version = "^2.0", features = ["full"] }
apex_macro = { path = "../apex_macro" }
