[package]
name = "apex_components"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
apex = { path = "../apex" }

[lints]
workspace = true
